### ISSUE TITLE
和你的构式来源项目部搭配啊

### ISSUE THREAD

**Issue by ghost** [kkzxak47/keycloak-services-social-wechatwork#2]
把两个项目放一起后只有一个生效

**Comment by kkzxak47** [comment]
不太明白，是哪两个项目？

**Comment by ghost** [comment]
谢谢拉，目前问题已经解决了非常感谢您能在闲暇时间回复我



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhong Xun"<notifications@github.com&gt;; 
发送时间: 2020年3月13日(星期五) 上午10:25
收件人: "kkzxak47/keycloak-services-social-wechatwork"<keycloak-services-social-wechatwork@noreply.github.com&gt;; 
抄送: "烟霏雾集"<1327800522@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kkzxak47/keycloak-services-social-wechatwork] 和你的构式来源项目部搭配啊 (#2)





 
Closed #2.
