### ISSUE TITLE
keycloak 19.0.1 兼容问题和部分解决办法

### ISSUE THREAD

**Issue by kslr** [kkzxak47/keycloak-services-social-wechatwork#22]
1. 依赖 fmt-maven-plugin 找不到
https://github.com/kkzxak47/keycloak-services-social-wechatwork/blob/900d048a391b523ea0a448fdc712350e461155a6/pom.xml#L21-L23
    
    把 21 行的 com.coveo 改为 com.spotify.fmt
    把 23 行的版本号改到 2.19.0

3. agent id 为 null
https://github.com/kkzxak47/keycloak-services-social-wechatwork/blob/900d048a391b523ea0a448fdc712350e461155a6/src/main/java/org/keycloak/social/wechat/WechatWorkProviderConfig.java#L16-L18
    java 代码我不了解，也没找到 getConfig 从何而来，简单写死了返回

   不知道作者近期有没有时间解决一下

**Comment by fhchina** [comment]
这个getConfig应该是从界面里边输入设置的。但是Keycloak 19.0.1下，把cp themes/base/admin/resources/partials/realm-identity-provider-wechat-work.html $KEYCLOAK_HOME/themes/base/admin/resources/partials/
cp themes/base/admin/resources/partials/realm-identity-provider-wechat-work-ext.html $KEYCLOAK_HOME/themes/base/admin/resources/partials/ 这两个文件拷贝之后，界面依然没有改变。因此也无法从界面中输入
###

**Comment by kslr** [comment]
> 这个getConfig应该是从界面里边输入设置的。但是Keycloak 19.0.1下，把cp themes/base/admin/resources/partials/realm-identity-provider-wechat-work.html $KEYCLOAK_HOME/themes/base/admin/resources/partials/ cp themes/base/admin/resources/partials/realm-identity-provider-wechat-work-ext.html $KEYCLOAK_HOME/themes/base/admin/resources/partials/ 这两个文件拷贝之后，界面依然没有改变。因此也无法从界面中输入

是的

**Comment by kslr** [comment]
转钉钉了
