### ISSUE TITLE
keycloak 9.0.0报错

### ISSUE THREAD

**Issue by mars198** [kkzxak47/keycloak-services-social-wechatwork#6]
hello 该模块在8.0.2实验了 完全没问题，在9.0.0版本报一堆错，能否帮忙看看什么问题

**Comment by lixiang957** [comment]
{
error: "invalid_request",
error_description: "Missing parameter: username"
}


wechat login error

**Comment by Janche** [comment]
升级 9.0的之后，有一个 createConfig方法，这个如何实现呀，或者9.0大佬这边如何兼容的
