### ISSUE TITLE
中文字段乱码

### ISSUE THREAD

**Issue by x1aoj1ang** [kkzxak47/keycloak-services-social-wechatwork#7]
02:45:49,048 INFO  [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (default task-84) {"errcode":0,"errmsg":"ok","userid":"2019111111","name":"?????????","department":[],"position":"",

这是日志中的显示,中文显示为?,并且在keycloak中也是乱码...

![image](https://user-images.githubusercontent.com/19269173/77982183-47eb7000-733e-11ea-8a17-fcd87c7c2926.png)

是要调整以下代码吗?

https://github.com/kkzxak47/keycloak-services-social-wechatwork/blob/93f0518a4c3ccb04a54b134531d1c928864c7ebf/src/main/java/org/keycloak/social/wechat/WechatWorkIdentityProvider.java#L352

另外想请教一下,如何对这个项目进行调试...感觉只能编译一下放进去重启测试...

非常感谢..

**Comment by kkzxak47** [comment]
乱码可能和系统环境默认编码有关系，不知道你部署在什么系统。Keycloak默认使用UTF-8，你可以把系统默认编码改成UTF-8试试。
Java我也不内行，我就是编译然后丢进去试……

**Comment by kkzxak47** [comment]
哦对了，也可以在bin/standalone.conf里加入JVM的启动选项，指定UTF8编码
```
#
#PRESERVE_JAVA_OPTS=true

#
# Specify options to pass to the Java VM.
#
if [ "x$JAVA_OPTS" = "x" ]; then
   JAVA_OPTS="-Xms512m -Xmx2048m -XX:MetaspaceSize=192M -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true"
   JAVA_OPTS="$JAVA_OPTS -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS -Djava.awt.headless=true"
else
   echo "JAVA_OPTS already set in environment; overriding default settings with values: $JAVA_OPTS"
fi

# whole app use UTF-8 encoding
JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF-8"
```
当然，如果你使用不同的启动方式，就要修改不同的conf文件。
