### ISSUE TITLE
关于兼容微信端的建议

### ISSUE THREAD

**Issue by x1aoj1ang** [kkzxak47/keycloak-services-social-wechatwork#8]
https://github.com/kkzxak47/keycloak-services-social-wechatwork/blob/93f0518a4c3ccb04a54b134531d1c928864c7ebf/src/main/java/org/keycloak/social/wechat/WechatWorkIdentityProvider.java#L258

改下这句代码就可以兼容微信那边了,

>         if (ua.contains("wxwork") || ua.contains("micromessenger")) {

强烈建议哈

**Comment by kkzxak47** [comment]
欢迎发PR呀

**Comment by wayne03111026** [comment]
请问下，这个插件集成到keycloak上，在企业微信扫完码后报了身份提供者认证错误这个要怎么解决呀？
[org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] Failed to make identity provider oauth callback: java.lang.NullPointerException

**Comment by wayne03111026** [comment]
找到错误了，我因为我的企业微信没有填写邮箱，导致程序有空制针从而导致了上面的身份提供者无法进行oauth回调。
解决：1、在企业微信加上邮箱账号即可回调成功；2、在代码中进行非空判断即可，测试不加企业邮箱也可以回调成功。
![image](https://user-images.githubusercontent.com/66346711/104981274-46ad4000-5a43-11eb-865b-f0302f60d5e6.png)

**Comment by wayne03111026** [comment]
图片查看：http://github-production-user-asset-6210df.s3.amazonaws.com/66346711/104981274-46ad4000-5a43-11eb-865b-f0302f60d5e6.png

**Comment by x1aoj1ang** [comment]
> 欢迎发PR呀

因为一直不懂怎么调试这种插件。。。所以。。。
想请教下当时是怎么开发的？要如何开发调试这种插件比较容易？好像没有文档（方便贴个链接吗，或者简单说下大概的方法，感谢）。。。
